Pin Alpine version
tubalainen/sparsnas_decoder pull request #19
Opened 2019-07-20 07:14 UTC by JariInc

`sparsnas.sh` doesn't run on current Alpine Edge. This PR pins the version to 3.7 where it still works, however it doesn't fix the underlying issue.

The issue was (IIRC) in line 54 where the command `busybox timeout` fails.

Also reordered commands to utilize Docker caching a bit better.

2019-07-20 07:49 UTC, fredrike requested changes
LGTM, just fix the additional white-space.

2019-07-20 07:49 UTC, fredrike commented on Dockerfile
> +
```suggestion

```

2019-07-20 07:52 UTC, fredrike commented
> The issue was (IIRC) in line 54 where the command `busybox timeout` fails.

Is there an alternative to [`busybox timeout`](https://github.com/JariInc/sparsnas_decoder/blob/b3ad5f1b62dbef5311ece834d56dffb13526e7dc/sparsnas.sh#L58) to fix it permanently?

2019-07-20 08:40 UTC, JariInc commented
> > The issue was (IIRC) in line 54 where the command `busybox timeout` fails.
> 
> Is there an alternative to [`busybox timeout`](https://github.com/JariInc/sparsnas_decoder/blob/b3ad5f1b62dbef5311ece834d56dffb13526e7dc/sparsnas.sh#L58) to fix it permanently?

I can investigate this more, now that I have a working setup.

2019-07-24 05:52 UTC, fredrike commented on Dockerfile
> +
@JariInc could you please use this change so I can merge the code.

2019-07-24 06:45 UTC, JariInc commented
I guess it was just about the `-t` parameter. I can't remember what issue I stumbled upon when I tried to fix it the first time couple months ago.

Now it's back using Alpine Edge and it's working fine without the `-t` parameter.

Although it would be wise to pin the Alpine version `rtl-sdr` comes from _ testing_ repository which is only available for Edge (Looks like it worked with 3.7 but wouldn't count on it).

2019-07-24 07:01 UTC, fredrike commented
> Although it would be wise to pin the Alpine version `rtl-sdr` comes from _ testing_ repository which is only available for Edge (Looks like it worked with 3.7 but wouldn't count on it).

Is it working now?

2019-07-24 07:01 UTC, fredrike approved these changes

2019-07-24 07:10 UTC, JariInc commented
> > Although it would be wise to pin the Alpine version `rtl-sdr` comes from _ testing_ repository which is only available for Edge (Looks like it worked with 3.7 but wouldn't count on it).
> 
> Is it working now?

Yeah, running fine.

2019-07-24 07:11 UTC, merged

2019-07-24 07:11 UTC, fredrike commented
Thank you for spotting this!